 // Access DOM elements
 const pic = document.getElementById("image");
 const affen = document.getElementById("affen");
 const akita = document.getElementById("akita");
 const bbd = document.getElementById("bbd");
 const frb = document.getElementById("frb");
 const chi = document.getElementById("chi");
 const corgi = document.getElementById("corgi");
 const dalma = document.getElementById("dalma");
 const dober = document.getElementById("dober");
 const elk = document.getElementById("elk");
 const frise = document.getElementById("frise");
 const gsheph = document.getElementById("gsheph");
 const ghound = document.getElementById("ghound");
 const husky = document.getElementById("husky");
 const wolfH = document.getElementById("wolfh");